from django.conf.urls import url, patterns
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout

urlpatterns = patterns("accounts.views",
                        url(r"^create_user", "createUser"),
                        url(r"^update_user", "updateUser"),
                        url(r"^update_setting_field", "updateSettingField"),
                        url(r"^search_by_email", "searchByEmail"),
                        url(r"^search_by_username", "searchByUsername"),
                        url(r"^add_friend", "addFriend"),
                        url(r"^create_group", "createGroup"),
                        url(r"^update_group/(\d+)", "updateGroup"),
                        url(r"^group_add_users/(\d+)", "addUsersToGroup"),
                        )

urlpatterns += patterns("accounts.api",
                        # manual refreshing/updating of campaign backend data
                        url(r"^register$", "registerUser"),
                        url(r"^login$", "login"),
                        url(r'logout', "logoutUser"),
                        url(r"^update$", "updateAccountProfileField"),
                        url(r"^settings/update$", "updateAccountSettingField"),
                        url(r"^settings/get$", "getAccountSettings"),
                        url(r"^search/email", "searchUsersByEmail"),
                        url(r"^search/username", "searchUsersByUsername"),
                        url(r"^friends/new", "addFriend"),
                        url(r"^friends/add_by_phone", "addFriendByPhoneNumber"),
                        url(r"^friends/unfriend", "unfriend"),
                        url(r"^friends/list", "getFriends"),
                        url(r"^friends/(\d+)", "getFriend"),
                        url(r"^friends/facebook/all$", "getAllFacebookFriends"),
                        url(r"^syncFacebookFriends$", "syncFacebookFriends"),
                        url(r"^syncFacebookUser/([A-Za-z0-9_\.-]+)$", "syncFacebookUser"),
                        url(r"^getAccessToken$", "getAccessToken"),
                        url(r'^venmoTransaction$', 'venmoTransaction'),
                        url(r'^venmoGetUserFriendList$', 'venmoGetUserFriendList'),
                        url(r'^venmoGetUserInfo$', 'venmoGetUserInfo'),
                        url(r'^venmoGetAccessToken$', 'venmoGetAccessToken'),
                        url(r'^venmo_connect$', 'venmoConnect'),
                        url(r'^facebook_connect$', 'facebookConnect'),
                        url(r"^group/new", "createGroup"),
                        url(r"^group/list", "getGroups"),
                        url(r"^group/(\d+)/members", "getGroupMembers"),
                        url(r"^group/(\d+)/add_remove_members", "addRemoveUsersFromGroup"),
                        url(r"^group/(\d+)/members/remove", "removeUsersFromGroup"),
                        url(r"^group/(\d+)/update", "updateGroup"),
                        url(r"^group/(\d+)/remove_self", "removeSelfFromGroup"),
                        url(r"^group/(\d+)", "getGroup"),
                        url(r"^check_if_phone_users_registered", "checkIfPhoneUsersRegistered"),
                        url(r"^updateLocation", "updateUserLocation"),
                        )